spring:
  application:
    name: ${springboot.app.name:auth-server}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      default-url: http://stdstack-eureka-server:8761/eureka/
      defaultUrl: http://stdstack-eureka-server:8761/eureka/
      defaultZone: http://stdstack-eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

