spring:
  application:
    name: stdstack-auth-server

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultUrl: http://stdstack-eureka-server:8761/eureka/
      defaultZone: http://stdstack-eureka-server:8761/eureka/

